### ISSUE TITLE
Decorator issue tracking

### ISSUE THREAD

**Issue by benStre** [unyt-org/uix#106]
This is a list of open issues in third-party software related to decorators:
* [x] Decorators for default exports: https://github.com/swc-project/swc/issues/8681
* [ ] Infer value initialization from decorators: https://github.com/microsoft/TypeScript/issues/52559
* [ ] Segmentation fault in SWC ?? https://github.com/swc-project/swc/issues/8695
